apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf_db
    user: telegraf
    password: password
    isDefault: true
    basicAuth: false
    jsonData:
      httpMode: GET