FROM alpine:latest

RUN	apk update && apk add \
			openrc \
			vsftpd \
			openssl

RUN	rc-update add vsftpd default

COPY ./srcs/ ./srcs/

RUN mv /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.orig ;\
	mv /srcs/vsftpd.conf /etc/vsftpd/vsftpd.conf

RUN openssl req -newkey rsa:4096 \
	-x509 -sha256 -days 3650 -nodes \
	-out /etc/ssl/certs/vsftpd.crt \
	-keyout /etc/ssl/private/vsftpd.key \
	-subj "/C=FR/ST=Ile de France/L=Paris/O=42/OU=IT Department/CN=www.vsftpd.com"

CMD ./srcs/start.sh

EXPOSE 21
EXPOSE 40000