FROM alpine:3.13

RUN apk add --no-cache\
			vsftpd \
			openssl \
			telegraf \
			supervisor

COPY ./srcs/ ./srcs/

RUN mv /etc/vsftpd/vsftpd.conf /etc/vsftpd/vsftpd.conf.orig ;\
	mv /srcs/vsftpd.conf /etc/vsftpd/vsftpd.conf

RUN openssl req -newkey rsa:4096 \
	-x509 -sha256 -days 3650 -nodes \
	-out /etc/ssl/certs/vsftpd.crt \
	-keyout /etc/ssl/private/vsftpd.key \
	-subj "/C=FR/ST=Ile de France/L=Paris/O=42/OU=IT Department/CN=www.vsftpd.com"

RUN mkdir /etc/telegraf/ ;\
	mv /srcs/telegraf.conf /etc/telegraf/telegraf.conf

CMD ./srcs/start.sh

EXPOSE 21
EXPOSE 40000